---
#Usual VMware guest deployment variables for example_group group
vsphere_host: 172.16.100.9
vsphere_user: "administrator@vsphere.local"
vsphere_datacenter: "EODC"
client_folder: "TEST"
vsphere_folder: "/EODC/PreProd/TEST"
cluster_name: "VMware-HA-Cluster"
esxi_hosts: "esxi-3.mxt.local"
vswitch_name: vSwitch0
portgroup_name: VMNet_Vlan-546
vlan_id: 546
guest_network: VMNet_Vlan-546
guest_netmask: 255.255.255.248
guest_gateway: 41.231.7.105
guest_dns_server: 192.168.1.10
guest_domain_name: testAnsible
guest_id: centosGuest
guest_memory: 2048
guest_vcpu: 2
guest_template: Template_centos7
